### ISSUE TITLE
Migrating to arm-none-eabi-* from arm-elf

### ISSUE THREAD

**Issue by finger563** [sparkfun/Logomatic#11]
I'm trying to migrate this over from `arm-elf-gcc` to `arm-none-eabi-gcc`, and I've updated the makefiles to change the compiler / mcu settings and remove the WinARM settings, so that I can get a proper elf / FW.SFE out of it.  However, the code does not execute properly after the bootloader loads it.  Do you know of anything else that must change when moving to this different compiler?

**Comment by sielenk** [comment]
I am using a Linux toolchain, too. And I did not change much: https://github.com/sielenk/Logomatic/commits/mine/Firmware/Main/Makefile
Since the processor used does not have a FPU, I used the target `arm-softfloat-eabi`, though. Maybe that is your problem: try adding `-mfloat-abi=soft` to the compiler options.

**Comment by finger563** [comment]
Hmmm, yea that's what I thought; but sadly no luck. I'll keep trying and see what I can figure out :/

**Comment by finger563** [comment]
So I managed to get it working, and I didn't need the `-mfloat-abi=soft`, based on your example (I had split mine up and was trying to use the `arch` and `tune` parameters, which weren't working).  Final question: do you have any idea how to enable the `FIO`?  My old code (which was built using `CrossStudio`), was able to use it and I see the addresses defined in the header files, but for some reason I don't get any of my expected output when I use it in my code (works when I switch back to just using `IODIR/IOSET/IOCLR`, etc.).

**Comment by finger563** [comment]
Nevermind, figured out the issue. Thanks!
