### ISSUE TITLE
Safety spelt incorrectly 

### ISSUE THREAD

**Issue by garrettseepersad** [sparkfun/Logomatic#13]
"Saftey"

File: FW.SFE
`Saftey On = Y`

File: main.c
`strcpy(stringBuf, "MODE = 0\r\nASCII = N\r\nBaud = 4\r\nFrequency = 100\r\nTrigger Character = $\r\nText Frame = 100\r\nAD1.3 = N\r\nAD0.3 = N\r\nAD0.2 = N\r\nAD0.1 = N\r\nAD1.2 = N\r\nAD0.4 = N\r\nAD1.7 = N\r\nAD1.6 = N\r\nSaftey On = Y\r\n");`

**Comment by Grahldg** [comment]
It appears that it was [this line](https://github.com/sparkfun/Logomatic/blob/master/Firmware/Main/main.c#L608) that had the typo and that it was already corrected.  If that's the case I will close the issue.  If not, please send a link to the line/file and I will correct it.
